version: '3.8'
services:
    database:
        image: postgres:13
        container_name: postgres-app
        environment:
            POSTGRES_DB: user-profile
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypass
        ports:
            - 5432:5432
        volumes:
            - user-profile-vol:/var/lib/postgresql/data
            - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
            - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql

    cache:
        image: redis:6.0
        container_name: redis-app
        ports:
            - 6379:6379

    # app:
    #     container_name: nest-app
    #     restart: always
    #     build: .
    #     ports:
    #         - '80:3000'
    #     links:
    #         - database
    #         - cache
    #     depends_on:
    #         - database
    #         - cache
    #     env_file:
    #         - .env

volumes:
    user-profile-vol:
